TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote__c/Tax_Quote__c.object-meta.xml
<CustomObject>
    <label>Tax Quote</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Tax Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Ship To City</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;US&quot;</defaultValue>
    <label>Ship To Country</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Ship To State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
            <value>
                <fullName>NM</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Ship To Street</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote__c/fields/Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount__c</fullName>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Ship To Zip Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote_Item__c/Tax_Quote_Item__c.object-meta.xml
<CustomObject>
    <label>Tax Quote Item</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Tax Quote Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote_Item__c/fields/Sales_Item__c.field-meta.xml
<CustomField>
    <fullName>Sales_Item__c</fullName>
    <label>Sales Item</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote_Item__c/fields/Tax_Quote__c.field-meta.xml
<CustomField>
    <fullName>Tax_Quote__c</fullName>
    <label>Tax Quote</label>
    <referenceTo>Tax_Quote__c</referenceTo>
    <relationshipLabel>Tax Quote Items</relationshipLabel>
    <relationshipName>Tax_Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote_Item__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/classes/taxQuoteController.cls
public with sharing class taxQuoteController {
    
        private static API_Setting__mdt getCredentials(String IntegrationName){
        String org='Sandbox';
        //check if is sandbox
        Boolean isSandBox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
        
        If(!isSandbox){
            org = 'PROD';
        }
        else{
            // assuming all sandboxes will use same testing endpoint
            org = 'Sandbox';
        }
        
        //get endpoint and credentials
        return [select id,Environment__c, Endpoint__c, Username__c,Password__c from API_Setting__mdt WHERE Integration__c = :IntegrationName and Environment__c =: org limit 1];
    }
    
    @AuraEnabled
    public static List<Tax_Quote_Item__c> createTaxQuoteItems(String taxQuoteItems){
        List<Tax_Quote_Item__c> quoteItems = (List<Tax_Quote_Item__c>)System.JSON.deserialize(taxQuoteItems, List<Tax_Quote_Item__c>.class);
        if(quoteItems != null && !quoteItems.isEmpty()){
            insert quoteItems;
        }
        return quoteItems;
    }
    
    @AuraEnabled
    public static List<WrapperClass> calculateTax(String quoteItems, String taxQuoteID){
        Integer lineItemNumber = 1;

        Tax_Quote__c tquote = [SELECT ID, Street__c, City__c, State__c, Zip_Code__c, Country__c FROM Tax_Quote__c WHERE Id = :taxQuoteID LIMIT 1];
        List<Tax_Quote_Item__c> taxQuoteItems = (List<Tax_Quote_Item__c>)System.JSON.deserialize(quoteItems, List<Tax_Quote_Item__c>.class);
 
		// JSON generator class
		JSONGenerator gen = JSON.createGenerator(true);
     
        // Write data to the JSON string.
        gen.writeStartObject();
        gen.writeStringField('TaxDate', '2020-02-27');
        gen.writeStringField('Division', 'C0001');
        gen.writeFieldName('SalesItems');
        gen.writeStartArray();
        
        for(Tax_Quote_Item__c tqi : taxQuoteItems){
            gen.writeStartObject();
            gen.writeFieldName('SalesItem');

            gen.writeStartObject();
            gen.writeObjectField('LineItemNumber', lineItemNumber);
            gen.writeObjectField('SalesItemId', tqi.Sales_Item__c);
            gen.writeObjectField('Quantity', 1);
            gen.writeObjectField('ExtendedPrice', tqi.Amount__c);
            
            gen.writeFieldName('Address');
            gen.writeStartObject();
            gen.writeObjectField('StreetAddress1', tquote.Street__c);
            gen.writeObjectField('City', tquote.City__c);
            gen.writeObjectField('MainDivision', tquote.State__c);
            gen.writeObjectField('PostalCode', tquote.Zip_Code__c);
            gen.writeObjectField('Country', 'USA');
            gen.writeEndObject();
            gen.writeEndObject();
            gen.writeEndObject();

            LineItemNumber++;
        }
        gen.writeEndArray();
        gen.writeEndObject();

        // Get the JSON string.
        String payload =gen.getAsString();
        
        API_Setting__mdt mdt = [SELECT Endpoint__c, Username__c, Password__c, Label FROM API_Setting__mdt WHERE Label = 'SnapLogic Tax Quote- Sandbox' LIMIT 1];
        String endPointURL = mdt.Endpoint__c;
        String userName = mdt.Username__c;
        String password = mdt.Password__c;
        
        // Specify the required user name and password to access the endpoint 
        // As well as the header and header information 
        Blob headerValue = Blob.valueOf(userName + ':' + password);
        String authorizationHeader = 'BASIC ' +EncodingUtil.base64Encode(headerValue);
        Httprequest request = new HttpRequest();
        Http http = new Http();
        request.setBody(payload);          
        request.setMethod('POST');
        request.setEndpoint(endPointURL);
        request.setHeader('Content-Type', 'application/json');
        // Header info with remote server user name and password
        request.setHeader('Authorization', authorizationHeader);
        // timeout in milliseconds       
        request.setTimeout(120000);          
        //Making call to external REST API
        HttpResponse response = http.send(request);  
        String jsonString = response.getBody();
        System.debug('jsonString '+jsonString);
        List<WrapperClass> wrapperList = new List<WrapperClass>();
        List<JSON2Apex> jsItems = JSON2Apex.parse(jsonString);
        List<JSON2Apex.LineItems> lineItems = jsItems[0].LineItems;
        
        Boolean check=false;
        for(integer i = 0; i<taxQuoteItems.size() ; i++){
            WrapperClass wc = new WrapperClass();
            if(lineItems[i].LineItem.TaxApplicabilityCode == 'INVALID'){
                wc.hasError = true;
                wc.Error = lineItems[i].LineItem.Status;
                check = true;
                taxQuoteItems[i].Tax_Amount__c = null;
                taxQuoteItems[i].Tax_Rate__c  = null;
            }
            else{
                wc.hasError = false;
                wc.Error = '';
                taxQuoteItems[i].Tax_Amount__c = Decimal.valueOf(lineItems[i].LineItem.TotalTax);
                if(taxQuoteItems[i].Tax_Amount__c == 0.00){
                    taxQuoteItems[i].Tax_Rate__c  = 0;
                }else{
                    taxQuoteItems[i].Tax_Rate__c = (taxQuoteItems[i].Tax_Amount__c /taxQuoteItems[i].Amount__c) * 100;
                }
            }
                wc.taxQuoteItems=taxQuoteItems[i];
				wrapperList.add(wc);
        } 
        
        if(check){
			Tax_Quote__c tq = new Tax_Quote__c(Id = (id)taxQuoteID);
			delete tq;
        }
        else{
            if(taxQuoteItems != null && !taxQuoteItems.isEmpty())
            update taxQuoteItems;
        }
        return wrapperList;          
    }
    
    public class WrapperClass{
        @AuraEnabled
        public Tax_Quote_Item__c taxQuoteItems {get;set;}
        @AuraEnabled
        public Boolean hasError {get;set;}
        @AuraEnabled
        public String Error {get;set;}
    }
    
}