TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote__c/Tax_Quote__c.object-meta.xml
<CustomObject>
    <label>Tax Quote</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Tax Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Ship To City</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <label>Client Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;US&quot;</defaultValue>
    <label>Ship To Country</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Ship To State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
            <value>
                <fullName>NM</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Ship To Street</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote__c/fields/Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount__c</fullName>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Ship To Zip Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote_Item__c/Tax_Quote_Item__c.object-meta.xml
<CustomObject>
    <label>Tax Quote Item</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Tax Quote Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote_Item__c/fields/Sales_Item__c.field-meta.xml
<CustomField>
    <fullName>Sales_Item__c</fullName>
    <label>Sales Item</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote_Item__c/fields/Tax_Quote__c.field-meta.xml
<CustomField>
    <fullName>Tax_Quote__c</fullName>
    <label>Tax Quote</label>
    <referenceTo>Tax_Quote__c</referenceTo>
    <relationshipLabel>Tax Quote Items</relationshipLabel>
    <relationshipName>Tax_Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/objects/Tax_Quote_Item__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

TaxtQuotesAcxiom/force-app/main/default/classes/taxQuoteControllerTest.cls
@isTest
public class taxQuoteControllerTest {
    
    public static TestMethod void createTaxQuoteItems()
    {
        Tax_Quote__c tq = new Tax_Quote__c();
        tq.Opportunity_Name__c = 'Test';
        tq.Client_Name__c = 'Test';
        tq.Date__c = System.today();
        tq.Street__c = 'Test ABC';
        tq.State__c = 'AZ';
        tq.City__c = 'ABC';
		tq.Zip_Code__c = 'ABC123';
        tq.Country__c = 'US';
        insert tq;
        
        Tax_Quote_Item__c tqm = new Tax_Quote_Item__c();
        tqm.Sales_Item__c = 'Test';
        tqm.Amount__c = 100;
        tqm.Tax_Quote__c = tq.Id;
        tqm.Tax_Amount__c = 0;
        tqm.Tax_Rate__c = 0;
        insert tqm;
        
        Map<String,string> mymap = new Map<String,string>();
        String amt = String.valueOf(tqm.Amount__c);
        String rate = String.valueOf(tqm.Tax_Rate__c);
        String taxamt = String.valueOf(tqm.Tax_Amount__c);
        mymap.put('Sales_Item__c', tqm.Sales_Item__c);
        mymap.put('Amount__c', amt);
        mymap.put('Tax_Quote__c', tqm.Tax_Quote__c);
        String s = JSON.serialize(mymap);
        String newString = '['+ s + ']';
        System.debug('STTT '+newString);

        taxQuoteController.createTaxQuoteItems(newString);
    }
    
    @isTest
    public static void calculateTax()
    {
        Tax_Quote__c tq = new Tax_Quote__c();
        tq.Opportunity_Name__c = 'Test';
        tq.Client_Name__c = 'Test';
        tq.Date__c = System.today();
        tq.Street__c = 'Test ABC';
        tq.State__c = 'AZ';
        tq.City__c = 'ABC';
		tq.Zip_Code__c = 'ABC123';
        tq.Country__c = 'US';
        insert tq;
        
        Tax_Quote_Item__c tqm = new Tax_Quote_Item__c();
        tqm.Sales_Item__c = 'Test';
        tqm.Amount__c = 100;
        tqm.Tax_Quote__c = tq.Id;
        tqm.Tax_Amount__c = 0;
        tqm.Tax_Rate__c = 0;
        insert tqm;
        
        Map<String,string> mymap = new Map<String,string>();
        String amt = String.valueOf(tqm.Amount__c);
        String rate = String.valueOf(tqm.Tax_Rate__c);
        String taxamt = String.valueOf(tqm.Tax_Amount__c);
        mymap.put('Sales_Item__c', tqm.Sales_Item__c);
        mymap.put('Amount__c', amt);
        mymap.put('Tax_Quote__c', tqm.Tax_Quote__c);
        mymap.put('Id', tqm.Id);
        String s = JSON.serialize(mymap);
        String newString = '['+ s + ']';
        System.debug('STTT '+newString);
		Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Test_HttpResponse.HttpAutomatedJiraIssue());
        taxQuoteController.calculateTax(newString, tq.Id);
        Test.stopTest();
    }
}